name: Deploy RISE Portal
on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_site:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    defaults:
      run:
        # This tells GitHub to enter your specific folder
        working-directory: ./RISE-System-v2 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          # This tells GitHub where to find the lock file for caching
          cache-dependency-path: './RISE-System-v2/package-lock.json'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # This tells GitHub where the final 'dist' folder is inside the subfolder
          path: ./RISE-System-v2/dist 

  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4